name = "mission-control"
main = "src/index.js"
compatibility_date = "2026-03-01"

# =========================================================
# DURABLE OBJECTS
# =========================================================

[[durable_objects.bindings]]
name = "MISSION_STATE"
class_name = "MissionState"

[[durable_objects.bindings]]
name = "FLEET_STATE"
class_name = "FleetState"

# =========================================================
# D1 DATABASE
# =========================================================

[[d1_databases]]
binding = "schema"
database_name = "mission-control-db"
database_id = "5e5798c4-17bd-4f8b-88d8-04ae0905c861"

# =========================================================
# DURABLE OBJECT MIGRATIONS
# =========================================================

[[migrations]]
tag = "v1"
new_classes = [
  "MissionState",
  "FleetState"
]